"""Generate the standalone stdlib Python source used by approved analyses."""

from __future__ import annotations

from typing import Any


def build_analysis_source(plan: dict[str, Any]) -> str:
    """Return reviewable standalone source for one supported operation plan."""

    operation_lines = "\n".join(f"# - {step['title']}: {step['description']}" for step in plan["steps"])
    return f'''"""Generated by gm-science's deterministic Data Analyst.

Review this file together with the persisted analysis plan before execution.
"""

# Planned operations:
{operation_lines}

''' + _ANALYSIS_PROGRAM


_ANALYSIS_PROGRAM = r'''from __future__ import annotations

import csv
import html
import json
import math
import os
import statistics
from collections import defaultdict
from pathlib import Path
from typing import Any


def normalized_header(raw_header: list[str]) -> list[str]:
    counts: dict[str, int] = {}
    header: list[str] = []
    for index, raw_name in enumerate(raw_header, start=1):
        base = str(raw_name).strip() or f"column_{index}"
        counts[base] = counts.get(base, 0) + 1
        header.append(base if counts[base] == 1 else f"{base}_{counts[base]}")
    return header


def load_rows(path: Path, dataset_format: str) -> list[dict[str, Any]]:
    if dataset_format in {"csv", "tsv"}:
        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            reader = csv.reader(handle, delimiter="\t" if dataset_format == "tsv" else ",")
            try:
                header = normalized_header(next(reader))
            except StopIteration as exc:
                raise ValueError("Dataset is empty.") from exc
            rows = []
            for values in reader:
                if not values or all(not str(value).strip() for value in values):
                    continue
                rows.append({name: values[index] if index < len(values) else None for index, name in enumerate(header)})
            return rows
    if dataset_format == "jsonl":
        return [json.loads(line) for line in path.read_text(encoding="utf-8-sig").splitlines() if line.strip()]
    payload = json.loads(path.read_text(encoding="utf-8-sig"))
    if isinstance(payload, dict) and isinstance(payload.get("data"), list):
        payload = payload["data"]
    elif isinstance(payload, dict):
        payload = [payload]
    return list(payload)


def number(value: Any) -> float | None:
    if value is None or isinstance(value, bool):
        return None
    text = str(value).strip()
    if text.casefold() in {"", "na", "n/a", "null", "none", "nan"}:
        return None
    try:
        parsed = float(text)
    except (TypeError, ValueError):
        return None
    return parsed if math.isfinite(parsed) else None


def quantile(values: list[float], fraction: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    position = (len(ordered) - 1) * fraction
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return ordered[lower]
    return ordered[lower] + (ordered[upper] - ordered[lower]) * (position - lower)


def descriptive(values: list[float]) -> dict[str, Any]:
    if not values:
        return {"count": 0}
    return {
        "count": len(values),
        "mean": round(statistics.fmean(values), 8),
        "median": round(statistics.median(values), 8),
        "standard_deviation": round(statistics.stdev(values), 8) if len(values) > 1 else 0.0,
        "min": round(min(values), 8),
        "q1": round(quantile(values, 0.25) or 0.0, 8),
        "q3": round(quantile(values, 0.75) or 0.0, 8),
        "max": round(max(values), 8),
    }


def pearson(left: list[float], right: list[float]) -> float | None:
    if len(left) < 2 or len(left) != len(right):
        return None
    left_mean = statistics.fmean(left)
    right_mean = statistics.fmean(right)
    numerator = sum((x - left_mean) * (y - right_mean) for x, y in zip(left, right, strict=True))
    left_scale = math.sqrt(sum((x - left_mean) ** 2 for x in left))
    right_scale = math.sqrt(sum((y - right_mean) ** 2 for y in right))
    if left_scale == 0 or right_scale == 0:
        return None
    return round(numerator / (left_scale * right_scale), 8)


def histogram_svg(values: list[float], title: str, output_path: Path) -> None:
    if not values:
        return
    width, height, margin = 720, 420, 54
    bin_count = min(20, max(5, round(math.sqrt(len(values)))))
    low, high = min(values), max(values)
    counts = [0] * bin_count
    if low == high:
        counts[0] = len(values)
    else:
        for value in values:
            index = min(bin_count - 1, int((value - low) / (high - low) * bin_count))
            counts[index] += 1
    plot_width = width - margin * 2
    plot_height = height - margin * 2
    bar_width = plot_width / bin_count
    max_count = max(counts) or 1
    bars = []
    for index, count in enumerate(counts):
        bar_height = plot_height * count / max_count
        x = margin + index * bar_width + 1
        y = height - margin - bar_height
        bars.append(
            f'<rect x="{x:.2f}" y="{y:.2f}" width="{max(1, bar_width - 2):.2f}" '
            f'height="{bar_height:.2f}" fill="#27766d" />'
        )
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">'
        '<rect width="100%" height="100%" fill="#ffffff" />'
        f'<text x="{margin}" y="32" font-family="system-ui, sans-serif" font-size="18" fill="#18201f">'
        f'{html.escape(title)}</text>'
        f'<line x1="{margin}" y1="{height - margin}" x2="{width - margin}" y2="{height - margin}" stroke="#53605d" />'
        + "".join(bars)
        + f'<text x="{margin}" y="{height - 18}" font-family="system-ui, sans-serif" font-size="12" fill="#53605d">'
        f'{low:.4g}</text>'
        f'<text x="{width - margin}" y="{height - 18}" text-anchor="end" font-family="system-ui, sans-serif" '
        f'font-size="12" fill="#53605d">{high:.4g}</text></svg>'
    )
    output_path.write_text(svg, encoding="utf-8")


def safe_file_component(value: Any) -> str:
    text = "".join(character if character.isalnum() or character in {"-", "_", "."} else "_" for character in str(value))
    return text.strip("._")[:80] or "column"


def markdown_cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def analyze_dataset(dataset: dict[str, Any], operations: list[str], output_dir: Path) -> dict[str, Any]:
    rows = load_rows(Path(dataset["path"]), dataset["format"])
    numeric_columns = list(dataset.get("numeric_columns") or [])
    categorical_columns = list(dataset.get("categorical_columns") or [])
    all_columns = list(dict.fromkeys(key for row in rows for key in row))
    missing = {
        column: sum(1 for row in rows if row.get(column) is None or str(row.get(column)).strip().casefold() in {"", "na", "n/a", "null", "none", "nan"})
        for column in all_columns
    }
    numeric_values = {
        column: [parsed for row in rows if (parsed := number(row.get(column))) is not None]
        for column in numeric_columns
    }
    result: dict[str, Any] = {
        "artifact_id": dataset["artifact_id"],
        "title": dataset["title"],
        "row_count": len(rows),
        "column_count": len(all_columns),
        "missing_values": missing,
        "numeric_statistics": {column: descriptive(values) for column, values in numeric_values.items()},
        "figures": [],
        "assumption_checks": {
            "empty_dataset": len(rows) == 0,
            "zero_variance_columns": [column for column, values in numeric_values.items() if len(set(values)) <= 1],
            "numeric_missing_fraction": {
                column: round(1 - len(values) / max(1, len(rows)), 6) for column, values in numeric_values.items()
            },
        },
    }
    if "iqr_outliers" in operations:
        outliers = {}
        for column, values in numeric_values.items():
            q1, q3 = quantile(values, 0.25), quantile(values, 0.75)
            if q1 is None or q3 is None:
                continue
            spread = q3 - q1
            lower, upper = q1 - 1.5 * spread, q3 + 1.5 * spread
            outliers[column] = {
                "lower_bound": round(lower, 8),
                "upper_bound": round(upper, 8),
                "count": sum(value < lower or value > upper for value in values),
            }
        result["iqr_outliers"] = outliers
    if "pearson_correlation" in operations:
        correlations = []
        for left_index, left_name in enumerate(numeric_columns):
            for right_name in numeric_columns[left_index + 1 :]:
                pairs = [
                    (left, right)
                    for row in rows
                    if (left := number(row.get(left_name))) is not None
                    and (right := number(row.get(right_name))) is not None
                ]
                value = pearson([item[0] for item in pairs], [item[1] for item in pairs])
                correlations.append(
                    {"left": left_name, "right": right_name, "complete_pairs": len(pairs), "pearson_r": value}
                )
        result["pearson_correlations"] = correlations
    if "group_comparison" in operations and categorical_columns and numeric_columns:
        group_column = categorical_columns[0]
        grouped: dict[str, dict[str, list[float]]] = defaultdict(lambda: defaultdict(list))
        for row in rows:
            group = str(row.get(group_column) or "<missing>")
            for column in numeric_columns:
                parsed = number(row.get(column))
                if parsed is not None:
                    grouped[group][column].append(parsed)
        result["group_comparison"] = {
            "group_column": group_column,
            "groups": {
                group: {column: descriptive(values) for column, values in columns.items()}
                for group, columns in sorted(grouped.items())
            },
        }
    if "distribution" in operations:
        for column, values in numeric_values.items():
            if values:
                figure_path = output_dir / f"{dataset['artifact_id']}-{safe_file_component(column)}-histogram.svg"
                histogram_svg(
                    values,
                    f"{dataset['title']}: {column}",
                    figure_path,
                )
                result["figures"].append(figure_path.name)
                break
    return result


def report_markdown(payload: dict[str, Any]) -> str:
    lines = [
        f"# {payload['title']}",
        "",
        f"**Objective:** {payload['objective']}",
        "",
        "## Methods",
        "",
    ]
    lines.extend(f"- `{operation}`" for operation in payload["operations"])
    for dataset in payload["datasets"]:
        lines.extend(
            [
                "",
                f"## {dataset['title']}",
                "",
                f"- Rows: {dataset['row_count']}",
                f"- Columns: {dataset['column_count']}",
                f"- Missing cells: {sum(dataset['missing_values'].values())}",
                "",
                "### Numeric summary",
                "",
                "| Column | Count | Mean | Median | Std. dev. | Min | Q1 | Q3 | Max |",
                "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
            ]
        )
        for column, stats in dataset["numeric_statistics"].items():
            lines.append(
                "| " + " | ".join(
                    [markdown_cell(column), *[str(stats.get(key, "")) for key in ("count", "mean", "median", "standard_deviation", "min", "q1", "q3", "max")]]
                ) + " |"
            )
        checks = dataset["assumption_checks"]
        lines.extend(
            [
                "",
                "### Assumption checks",
                "",
                f"- Empty dataset: {checks['empty_dataset']}",
                f"- Zero-variance numeric columns: {', '.join(checks['zero_variance_columns']) or 'none'}",
            ]
        )
        if "iqr_outliers" in dataset:
            lines.extend(
                [
                    "",
                    "### IQR outliers",
                    "",
                    "| Column | Lower bound | Upper bound | Flagged values |",
                    "| --- | ---: | ---: | ---: |",
                ]
            )
            outliers = dataset["iqr_outliers"]
            if outliers:
                for column, values in outliers.items():
                    lines.append(
                        "| "
                        + " | ".join(
                            [
                                markdown_cell(column),
                                str(values["lower_bound"]),
                                str(values["upper_bound"]),
                                str(values["count"]),
                            ]
                        )
                        + " |"
                    )
            else:
                lines.append("| No eligible numeric columns |  |  | 0 |")
        if "pearson_correlations" in dataset:
            lines.extend(
                [
                    "",
                    "### Pearson correlations",
                    "",
                    "| Left | Right | Complete pairs | Pearson r |",
                    "| --- | --- | ---: | ---: |",
                ]
            )
            correlations = dataset["pearson_correlations"]
            if correlations:
                for item in correlations:
                    value = item["pearson_r"] if item["pearson_r"] is not None else "unavailable"
                    lines.append(
                        "| "
                        + " | ".join(
                            [
                                markdown_cell(item["left"]),
                                markdown_cell(item["right"]),
                                str(item["complete_pairs"]),
                                str(value),
                            ]
                        )
                        + " |"
                    )
            else:
                lines.append("| No eligible column pairs |  | 0 | unavailable |")
        comparison = dataset.get("group_comparison")
        if comparison:
            lines.extend(
                [
                    "",
                    f"### Group comparison by {markdown_cell(comparison['group_column'])}",
                    "",
                    "| Group | Column | Count | Mean | Median | Std. dev. |",
                    "| --- | --- | ---: | ---: | ---: | ---: |",
                ]
            )
            for group, columns in comparison["groups"].items():
                for column, stats in columns.items():
                    lines.append(
                        "| "
                        + " | ".join(
                            [
                                markdown_cell(group),
                                markdown_cell(column),
                                str(stats.get("count", "")),
                                str(stats.get("mean", "")),
                                str(stats.get("median", "")),
                                str(stats.get("standard_deviation", "")),
                            ]
                        )
                        + " |"
                    )
        if dataset.get("figures"):
            lines.extend(["", "### Figures", ""])
            lines.extend(f"- `{markdown_cell(name)}`" for name in dataset["figures"])
    if payload.get("warnings"):
        lines.extend(["", "## Limitations", ""])
        lines.extend(f"- {warning}" for warning in payload["warnings"])
    lines.extend(
        [
            "",
            "## Interpretation boundary",
            "",
            "This report is descriptive. Correlation is not causation, group summaries are not significance tests, and IQR flags are not automatic exclusions.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    input_path = Path(os.environ["GM_SCIENCE_INPUT_PATH"])
    output_dir = Path(os.environ["GM_SCIENCE_OUTPUT_DIR"])
    payload = json.loads(input_path.read_text(encoding="utf-8"))
    results = [analyze_dataset(dataset, payload["operations"], output_dir) for dataset in payload["datasets"]]
    summary = {
        "analysis_id": payload["analysis_id"],
        "title": payload["title"],
        "objective": payload["objective"],
        "operations": payload["operations"],
        "warnings": payload.get("warnings") or [],
        "datasets": results,
    }
    (output_dir / "analysis_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (output_dir / "analysis_report.md").write_text(report_markdown(summary), encoding="utf-8")
    print(f"Analysis {payload['analysis_id']} completed for {len(results)} dataset(s).")


if __name__ == "__main__":
    main()
'''
