import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { vi } from "vitest";
import { App } from "../app/src/App";
import type {
  BootstrapPayload,
  ClientDiagnostics,
  GmScienceArtifact,
  GmScienceAnalysis,
  GmScienceCapability,
  GmScienceDataset,
  GmScienceProject,
  GmScienceRun,
  PpxClientApi,
  RunEvent,
  RuntimeStatus,
  SessionSummary,
} from "../app/src/types";

function runtime(): RuntimeStatus {
  return {
    target: { id: "local-default", type: "local", name: "This Mac" },
    state: "healthy",
    summary: "ready",
    detail: "detail",
  };
}

function session(): SessionSummary {
  return {
    id: "session-a",
    agentId: "science-research",
    title: "New local session",
    updatedAt: "2026-07-10T10:00:00.000Z",
    lastMessagePreview: "",
  };
}

function project(overrides: Partial<GmScienceProject> = {}): GmScienceProject {
  return {
    id: "proj_123",
    name: "Protein design",
    description: "Binder discovery",
    agentContext: "Always cite sources.",
    workspacePath: "/tmp/gm-science/proj_123",
    sessionsCount: 0,
    artifactsCount: 0,
    enabledSkills: ["literature-review"],
    enabledConnectors: ["arxiv", "pubmed", "openalex"],
    enabledSpecialists: ["paper_reader", "research_reviewer"],
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-07-10T10:00:00.000Z",
    ...overrides,
  };
}

function scienceRun(overrides: Partial<GmScienceRun> = {}): GmScienceRun {
  return {
    taskId: "task-test",
    projectId: "proj_123",
    sessionId: "session-a",
    parentTaskId: "",
    kind: "local_python",
    title: "Python run",
    status: "completed",
    progressSummary: "Completed.",
    terminalSummary: "Completed.",
    lastError: "",
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-07-10T10:00:00.000Z",
    createdAtMs: 1,
    updatedAtMs: 2,
    endedAtMs: 2,
    canCancel: false,
    canRetry: true,
    logPreview: "",
    artifactIds: [],
    ...overrides,
  };
}

function scienceDataset(overrides: Partial<GmScienceDataset> = {}): GmScienceDataset {
  return {
    artifactId: "art-dataset",
    projectId: "proj_123",
    sessionId: "session-a",
    title: "Measurements",
    path: "/tmp/gm-science/proj_123/datasets/measurements/source.csv",
    mimeType: "text/csv",
    format: "csv",
    sourceName: "measurements.csv",
    sizeBytes: 48,
    rowCount: 3,
    profiledRowCount: 3,
    columnCount: 2,
    columnNames: ["group", "value"],
    profileArtifactId: "art-profile",
    profile: {
      version: 1,
      format: "csv",
      rowCount: 3,
      profiledRowCount: 3,
      columnCount: 2,
      columns: [
        {
          name: "group",
          inferredType: "string",
          nonNullCount: 3,
          missingCount: 0,
          missingFraction: 0,
          uniqueCount: 2,
          uniqueCountCapped: false,
          typeCounts: { string: 3 },
          topValues: [{ value: "A", count: 2 }],
        },
        {
          name: "value",
          inferredType: "integer",
          nonNullCount: 3,
          missingCount: 0,
          missingFraction: 0,
          uniqueCount: 3,
          uniqueCountCapped: false,
          typeCounts: { integer: 3 },
          topValues: [{ value: "1", count: 1 }],
          numeric: { count: 3, min: 1, max: 3, mean: 2, standardDeviation: 1 },
        },
      ],
      preview: [{ group: "A", value: "1" }],
      warnings: [],
    },
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-07-10T10:00:00.000Z",
    ...overrides,
  };
}

function scienceAnalysis(overrides: Partial<GmScienceAnalysis> = {}): GmScienceAnalysis {
  return {
    id: "analysis-test",
    projectId: "proj_123",
    sessionId: "session-a",
    title: "Compare groups",
    objective: "Compare groups and summarize values.",
    datasetArtifactIds: ["art-dataset"],
    plan: {
      version: 1,
      objective: "Compare groups and summarize values.",
      operations: ["data_quality", "descriptive_statistics", "group_comparison"],
      steps: [
        { id: "quality", title: "Check data quality", description: "Measure missing values and usable rows." },
        { id: "groups", title: "Compare groups", description: "Summarize numeric values by group." },
      ],
      datasets: [{ artifact_id: "art-dataset", title: "Measurements" }],
      assumptions: ["Group comparisons are descriptive and do not imply causality."],
      warnings: [],
    },
    source: "# Generated by gm-science\nprint('analyze')\n",
    taskId: "",
    status: "draft",
    run: null,
    reportArtifactId: "",
    figureArtifactIds: [],
    artifactIds: [],
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-07-10T10:00:00.000Z",
    ...overrides,
  };
}

function bootstrapPayload(): BootstrapPayload {
  return {
    runtime: runtime(),
    agents: [
      {
        id: "science-research",
        name: "science-research",
        description: "Local science agent",
        enabled: true,
        status: "healthy",
        tags: ["local"],
      },
    ],
    sessions: [session()],
    messages: [],
    selectedAgentId: "science-research",
    selectedSessionId: "session-a",
  };
}

function diagnostics(): ClientDiagnostics {
  return {
    mode: "local",
    target: { id: "local-default", type: "local", name: "This Mac" },
    openppxRoot: "/tmp/gm-science-runtime",
    openppxRootExists: true,
    pythonBin: "/tmp/gm-science-runtime/.venv/bin/python",
    globalConfigPath: "/tmp/.gm-science/global_config.json",
    globalConfigExists: true,
    clientApiBaseUrl: "http://127.0.0.1:8876",
    clientApiManagedByClient: true,
    clientApiHealthy: true,
    clientApiProcessRunning: true,
    agentCount: 1,
    sessionCacheEntries: 1,
    messageCacheEntries: 1,
    debugEnabled: false,
  };
}

function capabilities(projectValue: GmScienceProject = project()): GmScienceCapability[] {
  const definitions: Array<Pick<GmScienceCapability, "id" | "kind" | "name" | "description" | "status">> = [
    { id: "literature-review", kind: "skill", name: "Literature Review", description: "Review papers", status: "ready" },
    { id: "arxiv", kind: "connector", name: "arXiv", description: "Search preprints", status: "ready" },
    { id: "pubmed", kind: "connector", name: "PubMed", description: "Search biomedical papers", status: "needs_configuration" },
    { id: "openalex", kind: "connector", name: "OpenAlex", description: "Search scholarly works", status: "needs_configuration" },
    { id: "paper_reader", kind: "specialist", name: "Paper Reader", description: "Read papers", status: "ready" },
    { id: "research_reviewer", kind: "specialist", name: "Research Reviewer", description: "Review reports", status: "ready" },
  ];
  return definitions.map((item) => ({
    ...item,
    source: "built_in" as const,
    version: "",
    license: "",
    files: [],
    available: true,
    defaultEnabled: true,
    projectEnabled:
      item.kind === "skill"
        ? projectValue.enabledSkills.includes(item.id)
        : item.kind === "connector"
          ? projectValue.enabledConnectors.includes(item.id)
          : projectValue.enabledSpecialists.includes(item.id),
    statusDetail: item.status === "needs_configuration" ? "Configuration required." : "",
    metadata: item.kind === "specialist" ? { auto_dispatch: true } : {},
  }));
}

function installClient(overrides: Partial<PpxClientApi> = {}): {
  client: PpxClientApi;
  emit: (event: RunEvent) => void;
} {
  let listener: ((event: RunEvent) => void) | null = null;
  const client: PpxClientApi = {
    bootstrap: async () => bootstrapPayload(),
    getDiagnostics: async () => diagnostics(),
    saveConnectionSettings: async () => diagnostics(),
    runRuntimeCommand: async () => runtime(),
    listSessions: async () => ({ sessions: [session()] }),
    createSession: async () => ({ session: session() }),
    loadSession: async () => ({ messages: [] }),
    sendMessage: async () => ({ runId: "run-1" }),
    listGmScienceProjects: async () => ({ projects: [project()] }),
    createGmScienceProject: async (input) => ({ project: project({ id: "proj_new", name: input.name }) }),
    getGmScienceProject: async (projectId) => ({ project: project({ id: projectId }) }),
    listGmScienceCapabilities: async (projectId) => ({ projectId: projectId ?? "", items: capabilities() }),
    updateGmScienceProjectCapabilities: async (projectId, input) => {
      const updated = project({
        id: projectId,
        enabledSkills: input.enabledSkills,
        enabledConnectors: input.enabledConnectors,
        enabledSpecialists: input.enabledSpecialists,
      });
      return { project: updated, capabilities: capabilities(updated) };
    },
    listGmScienceArtifacts: async () => ({ artifacts: [] }),
    createGmScienceArtifact: async (projectId, input) => ({
      artifact: {
        id: "art-test",
        projectId,
        sessionId: input.sessionId ?? "",
        type: input.type,
        title: input.title,
        pathOrUrl: input.pathOrUrl ?? "",
        mimeType: input.mimeType ?? "",
        metadata: input.metadata ?? {},
        provenance: input.provenance ?? {},
        createdAt: "2026-07-10T10:00:00.000Z",
        updatedAt: "2026-07-10T10:00:00.000Z",
      },
    }),
    listGmScienceRuns: async () => ({ runs: [] }),
    getGmScienceRun: async (projectId, taskId) => ({ run: scienceRun({ projectId, taskId }) }),
    createGmSciencePythonRun: async (projectId, input) => ({
      run: scienceRun({ projectId, sessionId: input.sessionId ?? "", title: input.title }),
    }),
    cancelGmScienceRun: async (projectId, taskId) => ({
      run: scienceRun({ projectId, taskId, status: "cancelled" }),
    }),
    retryGmScienceRun: async (projectId, taskId) => ({
      run: scienceRun({ projectId, taskId: "task-retry", parentTaskId: taskId }),
    }),
    selectGmScienceDatasetFile: async () => null,
    listGmScienceDatasets: async () => ({ datasets: [] }),
    getGmScienceDataset: async () => {
      throw new Error("Dataset not found");
    },
    importGmScienceDataset: async () => {
      throw new Error("Dataset import is not configured in this test");
    },
    listGmScienceAnalyses: async () => ({ analyses: [] }),
    getGmScienceAnalysis: async () => {
      throw new Error("Analysis not found");
    },
    createGmScienceAnalysis: async () => {
      throw new Error("Analysis creation is not configured in this test");
    },
    runGmScienceAnalysis: async () => {
      throw new Error("Analysis execution is not configured in this test");
    },
    onRunEvent: (next) => {
      listener = next;
      return () => {
        if (listener === next) {
          listener = null;
        }
      };
    },
    ...overrides,
  };
  window.ppxClient = client;
  return { client, emit: (event) => listener?.(event) };
}

function artifact(overrides: Partial<GmScienceArtifact>): GmScienceArtifact {
  return {
    id: "art-default",
    projectId: "proj_123",
    sessionId: "session-a",
    type: "paper",
    title: "Artifact",
    pathOrUrl: "",
    mimeType: "application/json",
    metadata: {},
    provenance: {},
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-07-10T10:00:00.000Z",
    ...overrides,
  };
}

describe("gm-science App", () => {
  it("renders the Projects home", async () => {
    installClient();

    render(<App />);

    await screen.findByText("gm-science");
    expect(screen.getByRole("button", { name: /Protein design/ })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /\+ New project/ })).toBeInTheDocument();
  });

  it("creates a project from the New Project dialog and opens the workspace", async () => {
    const createGmScienceProject = vi.fn(async (input) => ({
      project: project({ id: "proj_new", name: input.name, description: input.description ?? "" }),
    }));
    installClient({
      listGmScienceProjects: async () => ({ projects: [] }),
      createGmScienceProject,
    });

    render(<App />);

    await screen.findByText("No projects yet");
    fireEvent.click(screen.getAllByRole("button", { name: /\+ New project/ })[0]);
    fireEvent.change(screen.getByPlaceholderText("Project name"), { target: { value: "Genome notes" } });
    fireEvent.change(screen.getByPlaceholderText("Describe what this project is about..."), {
      target: { value: "Cell line literature" },
    });
    fireEvent.change(screen.getByPlaceholderText("e.g., Always use GRCh38 for genome references..."), {
      target: { value: "Always use GRCh38." },
    });
    fireEvent.click(screen.getByRole("button", { name: "Create" }));

    await waitFor(() => {
      expect(createGmScienceProject).toHaveBeenCalledWith({
        name: "Genome notes",
        description: "Cell line literature",
        agentContext: "Always use GRCh38.",
      });
    });
    await screen.findByText("Genome notes is ready");
  });

  it("sends project-scoped messages from the workspace", async () => {
    const sendMessage = vi.fn(async () => ({ runId: "run-1" }));
    installClient({ sendMessage });

    render(<App />);

    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    await screen.findByText("Protein design is ready");
    fireEvent.change(screen.getByPlaceholderText("向本地 agent 发送任务..."), {
      target: { value: "Summarize the new papers" },
    });
    fireEvent.click(screen.getByRole("button", { name: "发送" }));

    await waitFor(() => {
      expect(sendMessage).toHaveBeenCalledWith({
        agentId: "science-research",
        sessionId: "session-a",
        projectId: "proj_123",
        text: "Summarize the new papers",
      });
    });
  });

  it("updates the selected Project connector allowlist from Customize", async () => {
    const updateGmScienceProjectCapabilities = vi.fn(async (projectId, input) => {
      const updated = project({
        id: projectId,
        enabledSkills: input.enabledSkills,
        enabledConnectors: input.enabledConnectors,
        enabledSpecialists: input.enabledSpecialists,
      });
      return { project: updated, capabilities: capabilities(updated) };
    });
    installClient({ updateGmScienceProjectCapabilities });

    render(<App />);

    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    fireEvent.click(await screen.findByRole("button", { name: "Customize" }));
    fireEvent.click(await screen.findByRole("button", { name: "Connectors" }));
    const pubmedSwitch = await screen.findByRole("switch", { name: "Enable PubMed" });
    expect(pubmedSwitch).toHaveAttribute("aria-checked", "true");
    fireEvent.click(pubmedSwitch);
    fireEvent.click(screen.getByRole("button", { name: "Save changes" }));

    await waitFor(() => {
      expect(updateGmScienceProjectCapabilities).toHaveBeenCalledWith("proj_123", {
        enabledSkills: ["literature-review"],
        enabledConnectors: ["arxiv", "openalex"],
        enabledSpecialists: ["paper_reader", "research_reviewer"],
      });
    });
  });

  it("searches dynamically discovered Skills and shows safe details", async () => {
    const items: GmScienceCapability[] = [
      ...capabilities(),
      {
        id: "local-analysis",
        kind: "skill",
        name: "Local Analysis",
        description: "Analyze local tabular datasets.",
        source: "local",
        version: "0.4.0",
        license: "Private",
        files: ["SKILL.md", "scripts/analyze.py"],
        available: true,
        defaultEnabled: false,
        projectEnabled: false,
        status: "ready",
        statusDetail: "",
        metadata: { file_count: 2 },
      },
    ];
    installClient({
      listGmScienceCapabilities: async (projectId) => ({ projectId: projectId ?? "", items }),
    });

    render(<App />);

    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    fireEvent.click(await screen.findByRole("button", { name: "Customize" }));
    fireEvent.click(await screen.findByRole("button", { name: "Skills" }));
    const panel = await screen.findByRole("region", { name: "Skills" });
    expect(within(panel).getByRole("heading", { name: /Built-in/ })).toBeInTheDocument();
    expect(within(panel).getByRole("heading", { name: /Local/ })).toBeInTheDocument();

    fireEvent.change(within(panel).getByRole("searchbox", { name: "Search skills" }), {
      target: { value: "local" },
    });

    expect(within(panel).queryByText("Literature Review")).not.toBeInTheDocument();
    expect(within(panel).getByText("Local Analysis")).toBeInTheDocument();
    fireEvent.click(within(panel).getByRole("button", { name: "Show details for Local Analysis" }));
    expect(within(panel).getByText("0.4.0")).toBeInTheDocument();
    expect(within(panel).getByText("Private")).toBeInTheDocument();
    expect(within(panel).getByText("scripts/analyze.py")).toBeInTheDocument();
    expect(within(panel).queryByText(/\/tmp\//)).not.toBeInTheDocument();
  });

  it("does not allow an unavailable connector to be enabled", async () => {
    const projectValue = project({ enabledConnectors: ["arxiv", "openalex"] });
    const items = capabilities(projectValue).map((item) =>
      item.id === "pubmed"
        ? {
            ...item,
            available: false,
            projectEnabled: false,
            status: "disabled" as const,
            statusDetail: "Disabled in global configuration.",
          }
        : item,
    );
    installClient({
      listGmScienceProjects: async () => ({ projects: [projectValue] }),
      listGmScienceCapabilities: async (projectId) => ({ projectId: projectId ?? "", items }),
    });

    render(<App />);

    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    fireEvent.click(await screen.findByRole("button", { name: "Customize" }));
    fireEvent.click(await screen.findByRole("button", { name: "Connectors" }));

    expect(await screen.findByRole("switch", { name: "Enable PubMed" })).toBeDisabled();
  });

  it("searches configured MCP connectors and shows redacted connection details", async () => {
    const items: GmScienceCapability[] = [
      ...capabilities(),
      {
        id: "mcp:filesystem",
        kind: "connector",
        name: "Filesystem",
        description: "Configured MCP server over stdio.",
        source: "local",
        version: "",
        license: "",
        files: [],
        available: true,
        defaultEnabled: false,
        projectEnabled: false,
        status: "ready",
        statusDetail: "Configured; connection is verified when runtime tools load.",
        metadata: {
          connector_type: "mcp",
          transport: "stdio",
          tool_prefix: "mcp_filesystem",
          command_name: "mcp-filesystem",
          configured_env_names: ["FILESYSTEM_TOKEN", "WORKSPACE_ROOT"],
          configured_header_names: [],
          runtime_header_names: ["X-Project-Id"],
          require_confirmation: true,
        },
      },
    ];
    installClient({
      listGmScienceCapabilities: async (projectId) => ({ projectId: projectId ?? "", items }),
    });

    render(<App />);

    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    fireEvent.click(await screen.findByRole("button", { name: "Customize" }));
    fireEvent.click(await screen.findByRole("button", { name: "Connectors" }));
    const panel = await screen.findByRole("region", { name: "Connectors" });
    fireEvent.change(within(panel).getByRole("searchbox", { name: "Search connectors" }), {
      target: { value: "filesystem" },
    });

    expect(within(panel).getByRole("heading", { name: /Local/ })).toBeInTheDocument();
    expect(within(panel).getByText("Filesystem")).toBeInTheDocument();
    fireEvent.click(within(panel).getByRole("button", { name: "Show details for Filesystem" }));
    expect(within(panel).getByText("stdio")).toBeInTheDocument();
    expect(within(panel).getByText("mcp_filesystem")).toBeInTheDocument();
    expect(within(panel).getByText("mcp-filesystem")).toBeInTheDocument();
    expect(within(panel).getByText("FILESYSTEM_TOKEN")).toBeInTheDocument();
    expect(within(panel).getByText("X-Project-Id")).toBeInTheDocument();
    expect(within(panel).getByText("Required")).toBeInTheDocument();
    expect(within(panel).queryByText(/secret/i)).not.toBeInTheDocument();
  });

  it("renders research artifact details with metadata fallbacks", async () => {
    installClient({
      listGmScienceArtifacts: async () => ({
        artifacts: [
          artifact({
            id: "art-paper",
            title: "Reliable Protein Folding",
            pathOrUrl: "https://example.test/folding",
            metadata: {
              year: 2024,
              authors: ["Ada Lovelace", "Grace Hopper"],
              source_names: ["arxiv", "pubmed"],
              doi: "10.1000/folding",
              citation_count: 12,
            },
          }),
          artifact({
            id: "art-report",
            type: "report",
            title: "Folding review",
            pathOrUrl: "/tmp/folding.md",
            metadata: { paper_artifact_ids: ["art-paper"] },
          }),
          artifact({
            id: "art-citation",
            type: "citation",
            title: "Reliable Protein Folding citation",
            metadata: { paper_artifact_id: "art-paper", report_artifact_id: "art-report" },
          }),
          artifact({ id: "art-malformed", title: "Metadata-free paper", metadata: {} }),
          artifact({
            id: "art-reading-note",
            type: "reading_note",
            title: "Folding reading note",
            metadata: {
              source_artifact_ids: ["art-paper"],
              evidence_scopes: ["metadata_abstract"],
              focus: "protein folding reliability",
              confidence_note: "Limited to abstract metadata.",
            },
          }),
          artifact({
            id: "art-critique",
            type: "critique_report",
            title: "Folding critique",
            metadata: {
              verdict: "revise",
              target_artifact_id: "art-report",
              findings: [
                {
                  severity: "major",
                  category: "evidence",
                  claim: "The central claim needs stronger support.",
                },
                {
                  severity: "minor",
                  category: "clarity",
                  claim: "Define the evaluation metric.",
                },
              ],
            },
          }),
        ],
      }),
    });

    render(<App />);
    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));

    expect(await screen.findByText("Reliable Protein Folding")).toBeInTheDocument();
    expect(screen.getByText("Ada Lovelace, Grace Hopper")).toBeInTheDocument();
    expect(screen.getByText("2024 · arxiv + pubmed · 12 citations")).toBeInTheDocument();
    expect(screen.getByText("DOI 10.1000/folding")).toBeInTheDocument();
    expect(screen.getByText(/folding\.md · 1 cited paper/)).toBeInTheDocument();
    expect(screen.getByText("Linked to report")).toBeInTheDocument();
    expect(screen.getByText("Metadata-free paper")).toBeInTheDocument();
    expect(screen.getByText("1 source · Evidence: abstract metadata")).toBeInTheDocument();
    expect(screen.getByText("Focus: protein folding reliability")).toBeInTheDocument();
    expect(screen.getByText("Limited to abstract metadata.")).toBeInTheDocument();
    expect(screen.getByText("revise")).toBeInTheDocument();
    expect(screen.getByText("1 major · 1 minor")).toBeInTheDocument();
    expect(screen.getByText("Target: art-report")).toBeInTheDocument();
    expect(screen.getByText("The central claim needs stronger support.")).toBeInTheDocument();
    expect(screen.getAllByRole("link", { name: "Open" })).toHaveLength(1);
    expect(screen.getByRole("link", { name: "Open" })).toHaveAttribute("href", "https://example.test/folding");
  });

  it("filters artifacts by title, type, and metadata", async () => {
    installClient({
      listGmScienceArtifacts: async () => ({
        artifacts: [
          artifact({ id: "art-paper", title: "Protein atlas", metadata: { doi: "10.1000/atlas" } }),
          artifact({ id: "art-report", type: "report", title: "Genome review" }),
        ],
      }),
    });

    render(<App />);
    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    await screen.findByText("Protein atlas");

    fireEvent.change(screen.getByPlaceholderText("Search artifacts..."), { target: { value: "report" } });

    expect(screen.queryByText("Protein atlas")).not.toBeInTheDocument();
    expect(screen.getByText("Genome review")).toBeInTheDocument();
  });

  it("creates a Project-scoped local Python run from the Runs panel", async () => {
    const createGmSciencePythonRun = vi.fn(async (projectId, input) => ({
      run: scienceRun({
        taskId: "task-created",
        projectId,
        sessionId: input.sessionId ?? "",
        title: input.title,
        status: "running",
        canCancel: true,
        canRetry: false,
      }),
    }));
    installClient({ createGmSciencePythonRun });

    render(<App />);
    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    fireEvent.click(await screen.findByRole("tab", { name: "Runs" }));
    fireEvent.click(screen.getByRole("button", { name: "New Python run" }));

    fireEvent.change(screen.getByPlaceholderText("Run title"), { target: { value: "Analyze measurements" } });
    fireEvent.change(screen.getByLabelText("Python source"), { target: { value: "print('analysis')" } });
    fireEvent.change(screen.getByLabelText("Input JSON"), { target: { value: '{"argv":["--fast"]}' } });
    fireEvent.click(screen.getByRole("button", { name: "Run" }));

    await waitFor(() => {
      expect(createGmSciencePythonRun).toHaveBeenCalledWith("proj_123", {
        title: "Analyze measurements",
        source: "print('analysis')",
        sessionId: undefined,
        input: { argv: ["--fast"] },
      });
    });
    expect(await screen.findByText("Analyze measurements")).toBeInTheDocument();
    expect(screen.getByText("running")).toBeInTheDocument();
  });

  it("imports, profiles, plans, reviews, and explicitly starts a data analysis", async () => {
    const dataset = scienceDataset();
    const draft = scienceAnalysis();
    const importGmScienceDataset = vi.fn(async () => ({ dataset }));
    const createGmScienceAnalysis = vi.fn(async () => ({ analysis: draft }));
    const runGmScienceAnalysis = vi.fn(async () => ({
      analysis: scienceAnalysis({
        taskId: "task-analysis",
        status: "running",
        run: scienceRun({
          taskId: "task-analysis",
          kind: "data_analysis",
          title: "Compare groups",
          status: "running",
          canCancel: true,
          canRetry: false,
        }),
      }),
    }));
    installClient({
      selectGmScienceDatasetFile: async () => ({ path: "/tmp/measurements.csv", name: "measurements.csv" }),
      importGmScienceDataset,
      createGmScienceAnalysis,
      runGmScienceAnalysis,
    });

    render(<App />);
    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    fireEvent.click(await screen.findByRole("tab", { name: "Data" }));
    expect(await screen.findByText("No datasets yet")).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Import" }));
    expect(await screen.findByRole("region", { name: "Measurements profile" })).toBeInTheDocument();
    expect(screen.getByText("3 × 2")).toBeInTheDocument();
    expect(screen.getByText("integer")).toBeInTheDocument();
    await waitFor(() => {
      expect(importGmScienceDataset).toHaveBeenCalledWith("proj_123", {
        sourcePath: "/tmp/measurements.csv",
        title: "measurements",
        sessionId: undefined,
      });
    });

    fireEvent.click(screen.getByRole("button", { name: "New analysis" }));
    fireEvent.change(screen.getByLabelText("Objective"), {
      target: { value: "Compare groups and summarize values." },
    });
    fireEvent.click(screen.getByRole("button", { name: "Create plan" }));

    expect(await screen.findByRole("region", { name: "Compare groups review" })).toBeInTheDocument();
    expect(screen.getByText("Check data quality")).toBeInTheDocument();
    expect(screen.getByText("Group comparisons are descriptive and do not imply causality.")).toBeInTheDocument();
    expect(screen.getByText("# Generated by gm-science", { exact: false })).toBeInTheDocument();
    expect(createGmScienceAnalysis).toHaveBeenCalledWith("proj_123", {
      title: undefined,
      objective: "Compare groups and summarize values.",
      datasetArtifactIds: ["art-dataset"],
      sessionId: undefined,
    });

    fireEvent.click(screen.getByRole("button", { name: "Approve & run" }));
    await waitFor(() => expect(runGmScienceAnalysis).toHaveBeenCalledWith("proj_123", "analysis-test"));
    expect(await screen.findByText("running")).toBeInTheDocument();
  });

  it("keeps the default Python source syntactically intact", async () => {
    const createGmSciencePythonRun = vi.fn(async (projectId, input) => ({
      run: scienceRun({ taskId: "task-default", projectId, title: input.title, status: "queued" }),
    }));
    installClient({ createGmSciencePythonRun });

    render(<App />);
    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    fireEvent.click(await screen.findByRole("tab", { name: "Runs" }));
    fireEvent.click(screen.getByRole("button", { name: "New Python run" }));
    fireEvent.click(screen.getByRole("button", { name: "Run" }));

    await waitFor(() => expect(createGmSciencePythonRun).toHaveBeenCalledTimes(1));
    const source = createGmSciencePythonRun.mock.calls[0][1].source;
    expect(source).toContain('"gm-science local Python run completed.\\n"');
    expect(source).not.toContain('"gm-science local Python run completed.\n"');
  });

  it("refreshes Artifacts when a Python run completes before polling starts", async () => {
    const listGmScienceArtifacts = vi.fn(async () => ({ artifacts: [] }));
    installClient({
      listGmScienceArtifacts,
      createGmSciencePythonRun: async (projectId, input) => ({
        run: scienceRun({
          taskId: "task-fast",
          projectId,
          title: input.title,
          status: "completed",
          canRetry: true,
        }),
      }),
    });

    render(<App />);
    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    await waitFor(() => expect(listGmScienceArtifacts).toHaveBeenCalledTimes(1));
    fireEvent.click(await screen.findByRole("tab", { name: "Runs" }));
    fireEvent.click(screen.getByRole("button", { name: "New Python run" }));
    fireEvent.click(screen.getByRole("button", { name: "Run" }));

    await waitFor(() => expect(listGmScienceArtifacts).toHaveBeenCalledTimes(2));
  });

  it("shows durable run output and exposes cancel and retry controls", async () => {
    const cancelGmScienceRun = vi.fn(async (projectId, taskId) => ({
      run: scienceRun({ projectId, taskId, title: "Long analysis", status: "cancelled" }),
    }));
    const retryGmScienceRun = vi.fn(async (projectId, taskId) => ({
      run: scienceRun({
        taskId: "task-retried",
        projectId,
        parentTaskId: taskId,
        title: "Failed analysis",
        status: "queued",
        canCancel: true,
        canRetry: false,
      }),
    }));
    installClient({
      listGmScienceRuns: async () => ({
        runs: [
          scienceRun({
            taskId: "task-running",
            title: "Long analysis",
            status: "running",
            canCancel: true,
            canRetry: false,
            progressSummary: "Processing batch 1",
            logPreview: "loaded 12 rows",
          }),
          scienceRun({
            taskId: "task-failed",
            title: "Failed analysis",
            status: "failed",
            canCancel: false,
            canRetry: true,
            lastError: "ValueError: invalid column",
          }),
        ],
      }),
      cancelGmScienceRun,
      retryGmScienceRun,
    });

    render(<App />);
    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    fireEvent.click(await screen.findByRole("tab", { name: "Runs" }));

    expect(await screen.findByText("Long analysis")).toBeInTheDocument();
    expect(screen.getByText("ValueError: invalid column")).toBeInTheDocument();
    fireEvent.click(screen.getByText("Log output"));
    expect(screen.getByText("loaded 12 rows")).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Cancel" }));
    await waitFor(() => expect(cancelGmScienceRun).toHaveBeenCalledWith("proj_123", "task-running"));
    const failedRun = screen.getByText("Failed analysis").closest("article");
    expect(failedRun).not.toBeNull();
    fireEvent.click(within(failedRun as HTMLElement).getByRole("button", { name: "Retry" }));
    await waitFor(() => expect(retryGmScienceRun).toHaveBeenCalledWith("proj_123", "task-failed"));
    expect(await screen.findByText("queued")).toBeInTheDocument();
  });

  it("refreshes artifacts when a run finishes", async () => {
    const paper = artifact({ id: "art-new", title: "Newly indexed paper" });
    const listGmScienceArtifacts = vi
      .fn()
      .mockResolvedValueOnce({ artifacts: [] })
      .mockResolvedValueOnce({ artifacts: [paper] });
    const { emit } = installClient({ listGmScienceArtifacts });

    render(<App />);
    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    await screen.findByText("No artifacts yet");

    await act(async () => {
      emit({ type: "run.finished", runId: "run-1", sessionId: "session-a" });
    });

    expect(await screen.findByText("Newly indexed paper")).toBeInTheDocument();
    expect(listGmScienceArtifacts).toHaveBeenCalledTimes(2);
  });

  it("refreshes artifacts after a run request fails", async () => {
    const listGmScienceArtifacts = vi.fn(async () => ({ artifacts: [] }));
    installClient({
      listGmScienceArtifacts,
      sendMessage: async () => {
        throw new Error("run failed");
      },
    });

    render(<App />);
    fireEvent.click(await screen.findByRole("button", { name: /Protein design/ }));
    await screen.findByText("No artifacts yet");
    fireEvent.change(screen.getByPlaceholderText("向本地 agent 发送任务..."), { target: { value: "search" } });
    fireEvent.click(screen.getByRole("button", { name: "发送" }));

    await screen.findByText("run failed");
    await waitFor(() => expect(listGmScienceArtifacts).toHaveBeenCalledTimes(2));
  });
});
