from __future__ import annotations

import json
import time
from pathlib import Path

import pytest

from openppx.gm_science.analysis.config import AnalysisConfig, parse_analysis_config
from openppx.gm_science.analysis.service import AnalysisService
from openppx.gm_science.data.config import DatasetConfig
from openppx.gm_science.data.service import DatasetService
from openppx.gm_science.execution.config import ScienceExecutionConfig
from openppx.gm_science.execution.service import ScienceExecutionService
from openppx.gm_science.store import GmScienceStore


def _services(tmp_path: Path) -> tuple[AnalysisService, DatasetService, ScienceExecutionService, GmScienceStore, str]:
    state = tmp_path / "state"
    store = GmScienceStore(state)
    project = store.create_project(name="Analysis", description="", agent_context="")
    datasets = DatasetService(
        store=store,
        config=DatasetConfig(
            enabled=True,
            max_file_size_bytes=1_000_000,
            profile_row_limit=1_000,
            preview_rows=10,
            max_columns=50,
            top_values_limit=10,
        ),
    )
    execution = ScienceExecutionService(
        data_dir=state,
        store=store,
        config=ScienceExecutionConfig(
            enabled=True,
            python_executable="",
            max_concurrent_runs=2,
            default_timeout_seconds=10,
            max_source_chars=200_000,
            max_log_preview_chars=6_000,
        ),
    )
    analysis = AnalysisService(
        store=store,
        dataset_service=datasets,
        execution_service=execution,
        config=AnalysisConfig(
            enabled=True,
            max_datasets=3,
            max_objective_chars=4_000,
            max_numeric_columns=20,
            max_group_categories=20,
        ),
    )
    return analysis, datasets, execution, store, project.id


def _wait(analysis: AnalysisService, project_id: str, analysis_id: str) -> dict:
    deadline = time.monotonic() + 10
    while time.monotonic() < deadline:
        payload = analysis.get_analysis(project_id, analysis_id)
        if payload["status"] in {"completed", "failed", "cancelled", "lost"}:
            return payload
        time.sleep(0.05)
    raise AssertionError(f"Analysis {analysis_id} did not finish")


def test_analysis_config_reads_and_bounds_values() -> None:
    parsed = parse_analysis_config(
        {
            "science": {
                "analysis": {
                    "enabled": False,
                    "maxDatasets": 0,
                    "maxObjectiveChars": 2,
                    "maxNumericColumns": 999,
                    "maxGroupCategories": 1,
                }
            }
        }
    )

    assert parsed.enabled is False
    assert parsed.max_datasets == 1
    assert parsed.max_objective_chars == 100
    assert parsed.max_numeric_columns == 200
    assert parsed.max_group_categories == 2


def test_create_draft_is_reviewable_and_does_not_start_task(tmp_path: Path) -> None:
    analysis, datasets, _execution, store, project_id = _services(tmp_path)
    source = tmp_path / "study.csv"
    source.write_text("group,x,y\nA,1,2\nA,2,4\nB,3,6\nB,100,8\n", encoding="utf-8")
    dataset = datasets.import_dataset(project_id=project_id, source_path=str(source))

    draft = analysis.create_draft(
        project_id=project_id,
        title="Group relationships",
        objective="Compare groups, inspect correlation, distribution, and outliers.",
        dataset_artifact_ids=[dataset["artifact_id"]],
    )

    assert draft["status"] == "draft"
    assert draft["task_id"] == ""
    assert draft["run"] is None
    assert draft["source"] if "source" in draft else True
    assert draft["plan"]["operations"] == [
        "data_quality",
        "descriptive_statistics",
        "distribution",
        "iqr_outliers",
        "pearson_correlation",
        "group_comparison",
    ]
    assert store.list_science_runs(project_id) == []
    detailed = analysis.get_analysis(project_id, draft["id"])
    assert "Generated by gm-science" in detailed["source"]


def test_approved_analysis_runs_once_and_links_reports_figures_and_inputs(tmp_path: Path) -> None:
    analysis, datasets, execution, store, project_id = _services(tmp_path)
    source = tmp_path / "study.csv"
    source.write_text("group,x,y\nA,1,2\nA,2,4\nB,3,6\nB,100,8\n", encoding="utf-8")
    dataset = datasets.import_dataset(project_id=project_id, source_path=str(source))
    draft = analysis.create_draft(
        project_id=project_id,
        objective="Compare groups and analyze correlations and outliers.",
        dataset_artifact_ids=[dataset["artifact_id"]],
    )

    running = analysis.run_analysis(project_id, draft["id"])
    finished = _wait(analysis, project_id, draft["id"])

    assert running["task_id"]
    assert finished["status"] == "completed"
    assert finished["report_artifact_id"]
    assert finished["figure_artifact_ids"]
    record = store.get_science_run(finished["task_id"])
    assert record is not None and record.kind == "data_analysis"
    artifacts = [store.get_artifact(artifact_id) for artifact_id in finished["artifact_ids"]]
    assert {artifact.type for artifact in artifacts if artifact is not None} >= {
        "code",
        "experiment_log",
        "report",
        "figure",
        "artifact_file",
    }
    for artifact in artifacts:
        assert artifact is not None
        assert artifact.provenance["analysis_id"] == draft["id"]
        assert artifact.provenance["source_artifact_ids"] == [dataset["artifact_id"]]
    report = store.get_artifact(finished["report_artifact_id"])
    assert report is not None
    report_text = Path(report.path_or_url).read_text(encoding="utf-8")
    assert "IQR outliers" in report_text
    assert "Pearson correlations" in report_text
    assert "Group comparison" in report_text
    assert "Figures" in report_text
    assert "Interpretation boundary" in report_text
    assert "completed" in execution.get_run(project_id, finished["task_id"])["status"]

    with pytest.raises(ValueError, match="already been approved"):
        analysis.run_analysis(project_id, draft["id"])


def test_unsupported_inference_is_exposed_as_plan_warning(tmp_path: Path) -> None:
    analysis, datasets, _execution, _store, project_id = _services(tmp_path)
    source = tmp_path / "study.csv"
    source.write_text("x,y\n1,2\n2,4\n", encoding="utf-8")
    dataset = datasets.import_dataset(project_id=project_id, source_path=str(source))

    draft = analysis.create_draft(
        project_id=project_id,
        objective="Run causal regression and report p-values.",
        dataset_artifact_ids=[dataset["artifact_id"]],
    )

    warning = draft["plan"]["warnings"][0]
    assert "causal" in warning
    assert "regression" in warning
    assert "inferential_test" in warning


def test_analysis_rejects_foreign_or_changed_dataset(tmp_path: Path) -> None:
    analysis, datasets, _execution, store, project_id = _services(tmp_path)
    other = store.create_project(name="Other", description="", agent_context="")
    source = tmp_path / "study.csv"
    source.write_text("x\n1\n2\n", encoding="utf-8")
    dataset = datasets.import_dataset(project_id=project_id, source_path=str(source))

    with pytest.raises(ValueError, match="was not found"):
        analysis.create_draft(
            project_id=other.id,
            objective="Analyze data.",
            dataset_artifact_ids=[dataset["artifact_id"]],
        )

    draft = analysis.create_draft(
        project_id=project_id,
        objective="Analyze data.",
        dataset_artifact_ids=[dataset["artifact_id"]],
    )
    Path(dataset["path"]).write_text("x\n999\n", encoding="utf-8")
    with pytest.raises(ValueError, match="changed after profiling"):
        analysis.run_analysis(project_id, draft["id"])


def test_analysis_sanitizes_dataset_column_names_for_figure_paths(tmp_path: Path) -> None:
    analysis, datasets, _execution, store, project_id = _services(tmp_path)
    source = tmp_path / "unusual.csv"
    source.write_text("../danger,value\n1,2\n2,4\n3,6\n", encoding="utf-8")
    dataset = datasets.import_dataset(project_id=project_id, source_path=str(source))
    draft = analysis.create_draft(
        project_id=project_id,
        objective="Analyze distributions.",
        dataset_artifact_ids=[dataset["artifact_id"]],
    )

    analysis.run_analysis(project_id, draft["id"])
    finished = _wait(analysis, project_id, draft["id"])

    assert finished["status"] == "completed"
    assert finished["figure_artifact_ids"]
    figure = store.get_artifact(finished["figure_artifact_ids"][0])
    assert figure is not None
    assert figure.path_or_url.endswith("danger-histogram.svg")
    assert ".." not in Path(figure.path_or_url).name


def test_analysis_uses_the_profiled_schema_for_irregular_csv_rows(tmp_path: Path) -> None:
    analysis, datasets, _execution, store, project_id = _services(tmp_path)
    source = tmp_path / "irregular.csv"
    source.write_text(
        ",value,value\nA,1,2,ignored\n,,\nB,3,4,ignored\n",
        encoding="utf-8",
    )
    dataset = datasets.import_dataset(project_id=project_id, source_path=str(source))
    assert dataset["column_names"] == ["column_1", "value", "value_2"]
    assert dataset["row_count"] == 2
    draft = analysis.create_draft(
        project_id=project_id,
        objective="Compare groups and inspect correlation.",
        dataset_artifact_ids=[dataset["artifact_id"]],
    )

    analysis.run_analysis(project_id, draft["id"])
    finished = _wait(analysis, project_id, draft["id"])

    assert finished["status"] == "completed"
    summary_artifact = next(
        artifact
        for artifact_id in finished["artifact_ids"]
        if (artifact := store.get_artifact(artifact_id)) is not None
        and artifact.title == "analysis_summary.json"
    )
    summary = json.loads(Path(summary_artifact.path_or_url).read_text(encoding="utf-8"))
    result = summary["datasets"][0]
    assert result["row_count"] == 2
    assert result["column_count"] == 3
    assert result["numeric_statistics"]["value"]["mean"] == 2.0
    assert result["numeric_statistics"]["value_2"]["mean"] == 3.0
    assert result["pearson_correlations"][0]["pearson_r"] == 1.0
    assert set(result["group_comparison"]["groups"]) == {"A", "B"}
